---
- name: install ruby
  openbsd_pkg:
    name: ruby%{{ ruby_version[ansible_os_family][ansible_distribution_version] }}
    state: present
- name: install bundler
  openbsd_pkg:
    name: ruby{{ ruby_version[ansible_os_family][ansible_distribution_version][0] }}{{ ruby_version[ansible_os_family][ansible_distribution_version][2] }}-bundler
    state: present
- name: create ruby version symlinks
  file:
    path: /usr/local/bin/{{ item }}
    src: /usr/local/bin/{{ item }}{{ ruby_version[ansible_os_family][ansible_distribution_version][0] }}{{ ruby_version[ansible_os_family][ansible_distribution_version][2] }}
    state: link
  with_items:
    - ruby
    - rake
    - gem
    - bundle
