---
- name: get current ruby version
  command: ruby --version
  register: current_ruby_version
  changed_when: true == false
  ignore_errors: true
- include: from_source.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- include: from_package.yml
  when: ansible_distribution == 'OpenBSD'
