---
- name: load OS specific variables
  include_vars: '{{ ansible_system|lower }}.yml'

- name: get current ruby version
  command: ruby{{ ruby_version[0] }}{{ ruby_version[2] }} --version
  register: current_ruby_version
  changed_when: true == false
  ignore_errors: true

- include: from_source.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: from_package.yml
  when: ansible_distribution == 'OpenBSD'
