---
- name: load release specific variables
  include_vars: '{{ ansible_system|lower }}.yml'

- include: from_source.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: from_package.yml
  when: ansible_distribution == 'OpenBSD'
